[workspace]
authors = ["Raniere Silva <Raniere.CostadaSilva@gesis.org>"]
channels = ["conda-forge"]
name = "rsecon25-mybinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandoc = ">=3.6.4,<4"
lxml = ">=5.3.2,<6"
